# Generated by Django 5.1.4 on 2024-12-21 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskhive_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedimage',
            name='created_at',
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
